### ISSUE TITLE
Understanding synapses database

### ISSUE THREAD

**Issue by neich** [ashapsoncoe/h01#1]
Hi,

I'm trying to build a graph from the synapses database and I've run into a problem. Since I don't have access to the BigQuery databases,I've downloaded the exported synapses data from:

`gs://h01-release/data/20210729/c3/synapses/exported`

With this I get 166 json files with about 900K synapses data in each. That matches the numbers presented in the paper that talk about 150M synapses. My problem is with the neuron ids.

I've created a simple Python script to analyze the data, and I have found that there are much more distinct neurons ids than it should be. My understanding is that there should be no more than 60K, and I've stopped the script when it had accounted for 6M different neuron ids.

Am I doing something wrong? Have the neuron ids some kind of "hidden" encoding? Any hints?

Thanks in advance

**Comment by ashapsoncoe** [comment]
Dear neich, apologies for the delayed reply. 

Each synapse should have the following structure: 

{"pre_synaptic_site":{"neuron_id":"5472528459","id":"19685462211","centroid":{"x":"461512","y":"196505","z":"256"},"type":"1","bounding_box":{"start":{"x":"461472","y":"196487","z":"240"},"size":{"x":"81","y":"37","z":"32"}},"class_label":"AXON","base_neuron_id":"5472528459"},"post_synaptic_partner":{"neuron_id":"5414315245","id":"19685462210","centroid":{"x":"461511","y":"196494","z":"256"},"type":"2","bounding_box":{"start":{"x":"461472","y":"196474","z":"240"},"size":{"x":"79","y":"40","z":"33"}},"class_label":"DENDRITE","base_neuron_id":"5472528717"},"location":{"x":"461512","y":"196499","z":"256"},"type":"2","confidence":0.95752114057540894,"bounding_box":{"start":{"x":"461472","y":"196474","z":"240"},"size":{"x":"81","y":"50","z":"33"}}}

For the neuron IDs you should use "pre_synaptic_site": "neuron_id", and "post_synaptic_partner": "neuron_id", rather than  "pre_synaptic_site": "id", and "post_synaptic_partner": "id", which are IDs for individual pre and post synaptic sites.

Let me know if this doesn't help and I'll look into it further.

**Comment by neich** [comment]
Hi,

Thanks,  that confirms my understanding of the meaning of the fields in the JSON files. My problem then is with the values of `"pre_synaptic_site": "neuron_id"`, and `"post_synaptic_partner": "neuron_id"`. I have scanned all the files counting the number of unique `"neuron_id"` values and I have found much more that it is supposed to be. I've created a [simple Python gist to show it](https://gist.github.com/neich/e9207ab21765079080a046b45ac2c3fc).

I've tested it with just the first file of the total 166 of the exported data, (downloaded from the h01-release site, resource `gs://h01-release/data/20210729/c3/synapses/exported/`) and the result is:

```
Loading export000000000000.json ...
Number of synapses read: 998235
Number of unique neurons in files: 1670817
```

As you can see, the number of unique neurons in this file is 1.6M which should be impossible since there should be less than 60K in **total**. Am I doing something wrong? Are the neuron ids encoded somehow? I can provide you a link to the JSON file if you want to run the test yourself.

I understand that this is a problem with the data, not with this repo, so thanks in advance to take your time to answer

**Comment by ashapsoncoe** [comment]
Ah - I think there is a misunderstanding of the meaning of the fields in
the json file. 'neuron_id' is actually the ID of a segment in the c3
segmentation - and the vast majority of segments are not identified neuron
types, because their cell bodies are not in the volume.

You can use the manually identified and classified cells' c3 agglomeration
IDs from here:
https://github.com/ashapsoncoe/h01/blob/main/agglo_20200916c3_cell_data.json,
to get the synapses to segments attached to identified cells from the main
synapses database.

Let me know if I can help any further

Alex

**Comment by neich** [comment]
Thanks, that makes much more sense. However, after doing some data analysis of the file you point out, I see that about 82% of the synapses in the JSON files from `gs://h01-release/data/20210729/c3/synapses/exported/` have a `neuron_id` (pre or post) that does not appear in either `base_seg` or `agglo_seg` fields of your file.

At the end, I'm just trying to build a graph from the h01 data and analyze it using [SiReNetA](https://github.com/mb-BCA/SiReNetA). I've inspected your repo and it seems that there is some script that does that  ([edge_list_to_graph.py](https://github.com/ashapsoncoe/h01/blob/main/edge_list_to_graph.py)) but I think that I don't have all the data to run it.

Is there any place with specific information about the meaning of all the fields in the data that you can download from the h01-release site?

Thanks in advance

**Comment by ashapsoncoe** [comment]
Apologies for the delayed reply. The file provided indeed only has the
IDs of segments with cell bodies in the volume and their classes.

The remaining classes of cell fragments (e.g. axon fragment, dendrite
fragment) can be derived from the raw skeleton node predictions (this
is what  edge_list_to_graph.py does).

For example, a segment could be classified as 'axon' if all of it's
skeleton nodes are predicted 'axon'. The raw skeleton data with
individual node predictions is available here:

gs://h01-release/data/20210601/c3/subcompartments/annotations

If this is infeasible (e.g. due to the size of the data), let me know
and I'll try to make some pre-computed segment types available to
download for all segments (or perhaps just the ones that form
synapses, since that is what you're interested in).

Best wishes

Alex
